/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.addMhsController;
import Model.mahasiswa;
import Model.matkul;

import javax.swing.*;

import static java.lang.Double.parseDouble;
import static java.lang.Integer.parseInt;

/**
 *
 * @author M Zayan Hafizh H
 */
public class addMahasiswa_matkul extends javax.swing.JFrame {
    private matkul new_matkul;
    private mahasiswa mhs; // Tambahkan variabel untuk referensi ke objek mahasiswa
    /**
     * Creates new form addMahasiswa_matkul
     */
    public addMahasiswa_matkul(mahasiswa mhs) { // Terima objek mahasiswa sebagai parameter konstruktor
        this.mhs = mhs; // Inisialisasi objek mahasiswa dari parameter konstruktor
        new_matkul = new matkul();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        namamatkul_txt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        nilaitugas_txt = new javax.swing.JTextField();
        nilaiuts_txt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        nilaiuas_txt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        nilaiakhir_txt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        grade_txt = new javax.swing.JTextField();
        submit_button = new javax.swing.JButton();
        nilaiakhir_button = new javax.swing.JButton();
        grade_button = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        jLabel1.setText("TAMBAHKAN DATA MATA KULIAH");

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel2.setText("Nama Matkul :");

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel3.setText("Nilai Tugas :");

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel6.setText("Nilai UAS :");

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel7.setText("Nilai UTS :");

        nilaiuas_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nilaiuas_txtActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel8.setText("Nilai Akhir :");

        nilaiakhir_txt.setEditable(false);
        nilaiakhir_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nilaiakhir_txtActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel9.setText("Grade :");

        grade_txt.setEditable(false);
        grade_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grade_txtActionPerformed(evt);
            }
        });

        submit_button.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        submit_button.setText("Submit");
        submit_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit_buttonActionPerformed(evt);
            }
        });

        nilaiakhir_button.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        nilaiakhir_button.setText("Tampilkan Nilai Akhir");
        nilaiakhir_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nilaiakhir_buttonActionPerformed(evt);
            }
        });

        grade_button.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        grade_button.setText("Tampilkan Grade");
        grade_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grade_buttonActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jButton2.setText("Kembali");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(186, 186, 186)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(29, 29, 29)
                                        .addComponent(jLabel9)
                                        .addGap(38, 38, 38))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(submit_button)
                                        .addGap(9, 9, 9)))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(namamatkul_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nilaitugas_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nilaiuts_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nilaiuas_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nilaiakhir_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(grade_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                                .addComponent(nilaiakhir_button)
                                .addGap(43, 43, 43)
                                .addComponent(grade_button)))))
                .addGap(56, 56, 56))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jLabel1)
                .addGap(68, 68, 68)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namamatkul_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(nilaitugas_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nilaiuts_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nilaiuas_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(nilaiakhir_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(grade_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submit_button)
                    .addComponent(nilaiakhir_button)
                    .addComponent(grade_button)
                    .addComponent(jButton2))
                .addGap(38, 38, 38))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nilaiakhir_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nilaiakhir_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nilaiakhir_txtActionPerformed

    private void grade_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grade_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_grade_txtActionPerformed

    private void submit_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit_buttonActionPerformed
        // TODO add your handling code here:
        mhs.tambahMatkul(new_matkul);
        System.out.println(mhs.getNama());
        addMhsController addMhs = new addMhsController();
        String nama_mhs = mhs.getNama();
        Integer nim = mhs.getNim();
        String kelas = mhs.getKelas();
        String dosen_pa = mhs.getDosen_pa();
        String lulus = mhs.getLulus();
        Double ipk = mhs.hitungIPK();
        addMhs.addIdentity(nim,nama_mhs,kelas,dosen_pa,lulus,ipk);


        // Tampilkan konfirmasi menggunakan JOptionPane
        int option = JOptionPane.showConfirmDialog(this,
                "Apakah Anda ingin menginputkan mata kuliah lagi?",
                "Konfirmasi",
                JOptionPane.YES_NO_OPTION);

        if (option == JOptionPane.YES_OPTION) {
            resetForm(); // Reset form jika pengguna ingin menginputkan lagi
        } else {
            // Jika tidak ingin input lagi, simpan semua matkul ke dalam objek mahasiswa
            saveAllMatkulToMahasiswa();
            JOptionPane.showMessageDialog(this, "Input mata kuliah selesai.");
            // Lakukan aksi lain, misalnya, kembali ke form sebelumnya atau menampilkan informasi lain
        }

        // Method untuk menyimpan semua matkul ke dalam objek mahasiswa
        private void saveAllMatkulToMahasiswa() {
            for (matkul m : listMatkul) {
                mhs.tambahMatkul(m);
            }
        }
    }//GEN-LAST:event_submit_buttonActionPerformed

    private void nilaiakhir_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nilaiakhir_buttonActionPerformed
        // TODO add your handling code here:
        new_matkul.setNamaMatkul(String.valueOf(namamatkul_txt));
        new_matkul.setNilaiTugas(parseDouble(nilaitugas_txt.getText()));
        new_matkul.setNilaiUTS(parseDouble(nilaiuts_txt.getText()));
        new_matkul.setNilaiUAS(parseDouble(nilaiuas_txt.getText()));
        new_matkul.setNilaiAkhir();
        nilaiakhir_txt.setText(String.valueOf(new_matkul.getNilaiAkhir()));

    }//GEN-LAST:event_nilaiakhir_buttonActionPerformed

    private void grade_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grade_buttonActionPerformed
        // TODO add your handling code here:
        new_matkul.setGrade();
        grade_txt.setText(String.valueOf(new_matkul.getGrade()));
    }//GEN-LAST:event_grade_buttonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void nilaiuas_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nilaiuas_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nilaiuas_txtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addMahasiswa_matkul.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addMahasiswa_matkul.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addMahasiswa_matkul.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addMahasiswa_matkul.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        // Buat objek mahasiswa dari jendela addMahasiswa_identitas
        mahasiswa mhs = new mahasiswa();
        mhs.setNama("Nama Mahasiswa"); // Ganti dengan nama mahasiswa yang sesuai
        mhs.setNim(1234567890); // Ganti dengan nim mahasiswa yang sesuai
        mhs.setKelas("Kelas Mahasiswa"); // Ganti dengan kelas mahasiswa yang sesuai
        mhs.setDosen_pa("Dosen PA Mahasiswa"); // Ganti dengan dosen PA mahasiswa yang sesuai

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addMahasiswa_matkul(mhs).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton grade_button;
    private javax.swing.JTextField grade_txt;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField namamatkul_txt;
    private javax.swing.JButton nilaiakhir_button;
    private javax.swing.JTextField nilaiakhir_txt;
    private javax.swing.JTextField nilaitugas_txt;
    private javax.swing.JTextField nilaiuas_txt;
    private javax.swing.JTextField nilaiuts_txt;
    private javax.swing.JButton submit_button;
    // End of variables declaration//GEN-END:variables
}
